CREATE TABLE `TB_SETTING` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `code` VARCHAR(255) UNIQUE NOT NULL DEFAULT "",
  `name` VARCHAR(255) NOT NULL DEFAULT "",
  `memo` VARCHAR(255) DEFAULT "",
  `value` VARCHAR(255) NOT NULL DEFAULT ""
);


CREATE TABLE `TB_ADMIN` (
  `id`     BIGINT PRIMARY KEY AUTO_INCREMENT,
  `userid` VARCHAR(255) UNIQUE NOT NULL,
  `passwd` VARCHAR(255) NOT NULL COMMENT 'SHA256 으로 저장',
  `nick`   VARCHAR(255),
  `phone`  VARCHAR(20)
);


CREATE TABLE `TB_TCP_SERVER` (
  `id`      BIGINT PRIMARY KEY AUTO_INCREMENT,
  `name`    VARCHAR(255) UNIQUE NOT NULL DEFAULT "",
  `ip_addr` VARCHAR(20) NOT NULL DEFAULT "",
  `port`    INT NOT NULL DEFAULT "80",
  `timeout` INT NOT NULL DEFAULT 300 COMMENT '단위: ms',
  `err_cnt` INT NOT NULL DEFAULT 0
);

