CREATE TABLE `TB_ADMIN` (
  `id`     BIGINT PRIMARY KEY AUTO_INCREMENT,
  `userid` VARCHAR(255) UNIQUE NOT NULL,
  `passwd` VARCHAR(255) NOT NULL COMMENT 'SHA256 으로 저장',
  `nick`   VARCHAR(255),
  `phone`  VARCHAR(20)
);
